#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Motor,  port1,           leftMotorF,    tmotorNone, openLoop)
#pragma config(Motor,  port2,           leftMotorB,    tmotorNone, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorNone, openLoop)
#pragma config(Motor,  port4,           lightServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           rightMotorB,   tmotorNone, openLoop)
#pragma config(Motor,  port10,          rightMotorF,   tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int MAX_SERVO = 100;
void moveLeft() {
	motor[leftMotorF]  = (vexRT[Ch3] + vexRT[Ch4])/2;
	motor[leftMotorB]  = (vexRT[Ch3] + vexRT[Ch4])/2;
}
void moveRight() {
	motor[rightMotorF]  = -(vexRT[Ch2] + vexRT[Ch1])/2;
	motor[rightMotorB]  = -(vexRT[Ch2] + vexRT[Ch1])/2;
}
void moveClaw() {
	motor[claw] = vexRT[Btn6U]*20 - vexRT[Btn6D]*20;
}
void move() {
	moveLeft();
	moveRight();
	moveClaw();
}
void stopMoving() {
	motor[leftMotorF]  = 0;
	motor[leftMotorB]  = 0;
	motor[rightMotorF]  = 0;
	motor[rightMotorB]  = 0;
}

int findBrightest() {
	int b = 1024;
	clearTimer(T1);
	while (time1[T1] < 11*1000) {
		motor[leftMotorB] = 50;
		motor[rightMotorF] = 50;
		if (SensorValue(lightSensor) < b) {
			b = SensorValue(lightSensor);
		}
	}
	stopMoving();
	return b;
}

int findBrightServo(){
	int b = 1024;
	for (int i = -MAX_SERVO; i < MAX_SERVO; i += 10){
		motor[port6] = i; //Set position, using i as the "angle"
		wait1Msec(200); //Wait for 10.2 second
		if (SensorValue(lightSensor) < b) {
			b = SensorValue(lightSensor);
		}
	}
	return b;
}
//b is the bright value found by find brighest
//t is the accepted range of error
int lightHorizontal(int b, int t) {
	clearTimer(T1);
	while(time1[T1] < 30*1000) {
		motor[leftMotorB] = 50;
		motor[rightMotorF] = 50;
		if (abs(SensorValue(lightSensor) - b) < t) {
			stopMoving();
			return time1[T1];
		}
	}
	return -1;
}
int lightVertical(int b, int t){
	for (int i = -MAX_SERVO; i < MAX_SERVO; i += 10){
		motor[port6] = i; //Set position
		wait1Msec(200); //Wait for 0.2 second
		if (abs(SensorValue(lightSensor) - b) < t) {
			return i; //If within bounds, stop and return current angle
		}
	}
	return -128;
}
//void lightVertical(int b, int t) {
	//a;
//}
void findLight() {
	int thresh = 2;
	int b = findBrightest();
	delay(2000);
	lightHorizontal(b, thresh);

	int bV = findBrightServo();
	delay(2000);
	lightVertical(bV, thresh);
}



task main() {
	while (true) {
		move();
		if (vexRT[Btn7L] == 1) {
			stopMoving();
			findLight();
			stopMoving();
		}
	}
}
