#pragma config(UART_Usage, UART2, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "BNSlib_HC05.h"

void sendSerial(int temp, int lit, int sal, int wind)
{
	char buffer[100]; // Create buffer to manipulate array of chars
	sprintf(buffer, "%d, %d, %d, %d", temp, lit, sal, wind); //Use sprintF to format the char array for input data
	writeDebugStream(buffer);
	bnsSerialSend(UART2, buffer);
}

task main()
{
	clearDebugStream();
	int counter = 0;
	while(1==1){
		sleep(1000);
		int x = SensorValue(lightSensor);
		sendSerial(x, 2 * x, 3 * x, 4 * x);
		counter++;
	}
}
