#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, in2,    tempSensor,    sensorReflection)
#pragma config(Sensor, in3,    saltSensor,    sensorReflection)
#pragma config(Sensor, in4,    windSensor,    sensorReflection)

#pragma config(Motor,  port1,           leftMotorF,    tmotorNone, openLoop)
#pragma config(Motor,  port2,           leftMotorB,    tmotorNone, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorNone, openLoop)
#pragma config(Motor,  port4,           lightServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           rightMotorB,   tmotorNone, openLoop)
#pragma config(Motor,  port10,          rightMotorF,   tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "BNSlib_HC05.h"

/*
Data buttons:

Btn7L: SUN find
Btn7R: POND find
Btn7D: DATA transmit
*/

task main()
{
	//Use Multitasking to transmit data while preforming tasks and movement
	startTask(dataCollection);
	startTask(readController);
}


//START OF SUBROUTINES------------------------------------------------------------------------

//IMPLEMENT
void findSun(){}




//IMPLEMENT
void findPond(){}


//END OF SUBROUTINES------------------------------------------------------------------------



//START OF TASKS------------------------------------------------------------------------------
//Tasks are used to multitask, run each task at the same time

/*
Controls movement and subroutines
VEX controller controls whether a subroutine should be preformed
*/
task readController(){
	//Read motor data
	//Execute Subroutines
	while(true){
		//Set motors to appropiate speedsd
		move();
		//Execute SUN Finder
		if (vexRT[Btn7L] == 1) {
			stopMoving();
			findSun(); //IMPLEMENT
		}
		//Execute AUTO Pond Trail
		if (vexRT[Btn7R] == 1) {
			stopMoving();
			findPond();//IMPLEMENT
		}
	}
}

/*
Transmits data to Raspberry Pi
*/
task dataCollection(){
	while(true)
	{
		//Data BUTTON
		if (vexRT[Btn7D] == 1){
			int temp = readTemp();
			int light = readLight();
			int salt = readSalt();
			int wind = readWind(); //This function takes at least 2 secs
			sendSerial(temp, light, salt, wind);
		}
	}
}
//END OF TASKS----------------------------------------------------------------------------------------






//START OF DATA COLLECTION UTIL FUNCTIONS--------------------------------------------------------------
/*
IMPLEMENT ALL!!!
Calibrate to scale
Use Linear Interpolation
*/

int readTemp(){
	int x = SensorValue(tempSensor)

}

/*
Return SensorValue
*/
int readLight(){
	int x = SensorValue(lightSensor)
	return x;
}

/*
Return SensorValue for light
*/
int readSalt(){
	int x = SensorValue(saltSensor)
}

/*
FIND Cutoff values
0: OFF
1: LOW
2: MED
3: HIGH
*/

//Pause for 2 secs, read number of rotations, then output number
int readWind(){
	ClearTimer(T1);

	while(time1[T1] < 2000){

	}

	int x = abs(SensorValue(windSensor)) //Read absolute value of rotations
}
//END OF DATA COLLECTION UTIL FUNCTIONS--------------------------------------------------------------


/*
Sends a set of 4 numbers, delimited by commas, to the raspberry pi
*/
void sendSerial(int temp, int light, int salt, int wind)
{
	// Create buffer to manipulate array of chars
	char buffer[100];
	//Use sprintF to format the char array for input data
	sprintf(buffer, "%d, %d, %d, %d", temp, lit, salt, wind);
	writeDebugStream(buffer);
	//Send buffer to UART
	bnsSerialSend(UART2, buffer);
}
